services:
  - type: web
    name: calorie-tracker-app
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "bundle exec rake db:migrate && bundle exec rails server -p 3000"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
